// ndvi.js — Vegetation index (NDVI) placeholder overlay (Leaflet image overlay).
//
// ILLUSTRATIVE PLACEHOLDER. The PNG is generated by
// scripts/generate-placeholders/generate_overlays.py (viridis ramp). To drop in a real
// Sentinel-2 NDVI raster, call `ndviLayer.swapWithRealRaster(map, url, bounds)` — see
// docs/swap-instructions.md.

// Bounds MUST match BBOX in generate_overlays.py.
// Leaflet bounds order: [[south, west], [north, east]]
const BOUNDS = [
  [1.205, 103.60],
  [1.475, 104.04],
];

const ACTIVE_OPACITY = 0.82;

export const ndviLayer = {
  id: 'ndvi-overlay',
  sourceId: 'ndvi-source',
  _layer: null,

  add(map) {
    if (this._layer) return;
    this._layer = L.imageOverlay('assets/overlays/ndvi.png', BOUNDS, {
      opacity: 0,
      interactive: false,
      className: 'data-overlay',
    }).addTo(map);
    if (this._layer.getElement()) this._layer.getElement().style.transition = 'opacity .5s ease';
  },

  setVisible(map, visible) {
    if (!this._layer) return;
    this._layer.setOpacity(visible ? ACTIVE_OPACITY : 0);
    if (visible && this._layer.bringToFront) this._layer.bringToFront();
  },

  // Swap the placeholder for a real georeferenced raster (same [[S,W],[N,E]] bounds).
  swapWithRealRaster(map, url, bounds = BOUNDS) {
    if (!this._layer) return;
    this._layer.setUrl(url);
    if (this._layer.setBounds) this._layer.setBounds(bounds);
  },
};
