// thermal.js — Land-surface-temperature (urban heat island) placeholder overlay.
//
// ILLUSTRATIVE PLACEHOLDER. The PNG is generated by
// scripts/generate-placeholders/generate_overlays.py (inferno ramp). To drop in a real
// Landsat 8/9 TIRS LST raster, call `thermalLayer.swapWithRealRaster(map, url, bounds)`
// — see docs/swap-instructions.md.

// Bounds MUST match BBOX in generate_overlays.py. Order: [[south, west], [north, east]]
const BOUNDS = [
  [1.205, 103.60],
  [1.475, 104.04],
];

const ACTIVE_OPACITY = 0.8;

export const thermalLayer = {
  id: 'thermal-overlay',
  sourceId: 'thermal-source',
  _layer: null,

  add(map) {
    if (this._layer) return;
    this._layer = L.imageOverlay('assets/overlays/thermal.png', BOUNDS, {
      opacity: 0,
      interactive: false,
      className: 'data-overlay',
    }).addTo(map);
    if (this._layer.getElement()) this._layer.getElement().style.transition = 'opacity .5s ease';
  },

  setVisible(map, visible) {
    if (!this._layer) return;
    this._layer.setOpacity(visible ? ACTIVE_OPACITY : 0);
    if (visible && this._layer.bringToFront) this._layer.bringToFront();
  },

  swapWithRealRaster(map, url, bounds = BOUNDS) {
    if (!this._layer) return;
    this._layer.setUrl(url);
    if (this._layer.setBounds) this._layer.setBounds(bounds);
  },
};
